# Generated by Django 5.1.15 on 2026-08-08 17:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedupRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dedup_version", models.CharField(max_length=40)),
                ("normalizer_version", models.CharField(max_length=50)),
                ("position_count_version", models.CharField(max_length=50)),
                ("source_precedence_version", models.CharField(max_length=50)),
                ("as_of", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("postings_considered", models.PositiveIntegerField(default=0)),
                ("candidate_pairs", models.PositiveIntegerField(default=0)),
                ("hard_key_merges", models.PositiveIntegerField(default=0)),
                ("rule_auto_merges", models.PositiveIntegerField(default=0)),
                ("review_pairs", models.PositiveIntegerField(default=0)),
                ("keep_separate_pairs", models.PositiveIntegerField(default=0)),
                ("hard_barrier_pairs", models.PositiveIntegerField(default=0)),
                ("vacancies_created", models.PositiveIntegerField(default=0)),
                ("episodes_created", models.PositiveIntegerField(default=0)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "dedup_run",
                "ordering": ["-as_of", "-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dedup_version", "as_of", "input_fingerprint"),
                        name="dedup_run_version_asof_input_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DedupDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dedup_version", models.CharField(max_length=40)),
                ("normalizer_version", models.CharField(max_length=50)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("HARD_KEY", "Hard key"),
                            ("RULE_SCORE", "Rule score"),
                            ("HUMAN", "Human"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("AUTO_MERGE", "Auto merge"),
                            ("REVIEW", "Review"),
                            ("KEEP_SEPARATE", "Keep separate"),
                            ("MERGE", "Merge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("feature_scores", models.JSONField(default=dict)),
                ("weights", models.JSONField(default=dict)),
                ("blocking_evidence", models.JSONField(default=dict)),
                ("hard_barriers", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "observation_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_decisions_as_a",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "observation_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_decisions_as_b",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "posting_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_decisions_as_a",
                        to="observations.posting",
                    ),
                ),
                (
                    "posting_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_decisions_as_b",
                        to="observations.posting",
                    ),
                ),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="vacancies.deduprun",
                    ),
                ),
            ],
            options={
                "db_table": "dedup_decision",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_version", models.CharField(max_length=40)),
                (
                    "current_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED_OBSERVED", "Closed observed")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("closed_observed_at", models.DateTimeField(blank=True, null=True)),
                ("current_episode_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_vacancies",
                        to="observations.posting",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_identities",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "vacancy",
            },
        ),
        migrations.CreateModel(
            name="DedupReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MERGED", "Merged"),
                            ("KEPT_SEPARATE", "Kept separate"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolution_reason", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "algorithm_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_item",
                        to="vacancies.dedupdecision",
                    ),
                ),
                (
                    "vacancy_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items_as_a",
                        to="vacancies.vacancy",
                    ),
                ),
                (
                    "vacancy_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items_as_b",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "dedup_review_item",
            },
        ),
        migrations.CreateModel(
            name="VacancyEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("episode_number", models.PositiveIntegerField()),
                ("opened_observed_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("closed_observed_at", models.DateTimeField(blank=True, null=True)),
                ("reappearance_gap_days", models.PositiveIntegerField(blank=True, null=True)),
                ("positions_count", models.PositiveIntegerField(blank=True, null=True)),
                ("multi_hire_possible", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED_OBSERVED", "Closed observed")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episodes",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "vacancy_episode",
                "ordering": ["vacancy_id", "episode_number"],
            },
        ),
        migrations.CreateModel(
            name="PositionCountEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("extractor_version", models.CharField(max_length=50)),
                ("positions_count", models.PositiveIntegerField(blank=True, null=True)),
                ("multi_hire_possible", models.BooleanField(default=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXPLICIT_NUMERIC", "Explicit numeric"),
                            ("MULTI_HIRE_SIGNAL", "Multi-hire signal"),
                            ("NOT_DISCLOSED", "Not disclosed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("raw_evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_count_evidence",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "vacancy_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_count_evidence",
                        to="vacancies.vacancyepisode",
                    ),
                ),
            ],
            options={
                "db_table": "position_count_evidence",
            },
        ),
        migrations.CreateModel(
            name="VacancyLifecycleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("STILL_ACTIVE", "Still active"),
                            ("CLOSED_OBSERVED", "Closed observed"),
                            ("REAPPEARED", "Reappeared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("supporting_postings", models.JSONField(default=list)),
                ("reason", models.TextField()),
                ("dedup_version", models.CharField(max_length=40)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="vacancies.vacancyepisode",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "vacancy_lifecycle_event",
            },
        ),
        migrations.CreateModel(
            name="VacancyPostingMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_version", models.CharField(max_length=40)),
                (
                    "link_method",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("HARD_KEY", "Hard key"),
                            ("RULE_SCORE", "Rule score"),
                            ("HUMAN", "Human"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_precedence_rank", models.PositiveSmallIntegerField()),
                (
                    "canonical_evidence_role",
                    models.CharField(
                        choices=[("CANONICAL", "Canonical"), ("SUPPORTING", "Supporting")],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dedup_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resulting_memberships",
                        to="vacancies.dedupdecision",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancy_memberships",
                        to="observations.posting",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "vacancy_posting_membership",
            },
        ),
        migrations.CreateModel(
            name="VacancyMembershipEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LINK", "Link"),
                            ("REASSIGN", "Reassign"),
                            ("MERGE_IDENTITY", "Merge identity"),
                            ("HUMAN_CONFIRM", "Human confirm"),
                            ("CANONICAL_PROMOTE", "Canonical promote"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_events",
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "from_vacancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_events_from",
                        to="vacancies.vacancy",
                    ),
                ),
                (
                    "to_vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_events_to",
                        to="vacancies.vacancy",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="vacancies.vacancypostingmembership",
                    ),
                ),
            ],
            options={
                "db_table": "vacancy_membership_event",
            },
        ),
        migrations.AddConstraint(
            model_name="dedupdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("posting_a", models.F("posting_b")), _negated=True),
                name="dedup_decision_distinct_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="dedupdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 1)),
                    _connector="OR",
                ),
                name="dedup_decision_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dedupdecision",
            constraint=models.UniqueConstraint(
                fields=("dedup_run", "posting_a", "posting_b", "method"),
                name="dedup_decision_run_pair_method_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["identity_version", "current_status"], name="vacancy_identit_b98b80_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("first_seen_at"))),
                name="vacancy_seen_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_observed_at__isnull", True),
                    ("closed_observed_at__gte", models.F("first_seen_at")),
                    _connector="OR",
                ),
                name="vacancy_closed_after_first_seen",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("merged_into__isnull", True),
                    models.Q(("id", models.F("merged_into")), _negated=True),
                    _connector="OR",
                ),
                name="vacancy_not_merged_into_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyepisode",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "episode_number"), name="vacancy_episode_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("positions_count__isnull", True), ("positions_count__gt", 0), _connector="OR"
                ),
                name="vacancy_episode_positions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("opened_observed_at"))),
                name="vacancy_episode_seen_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_observed_at__isnull", True),
                    ("closed_observed_at__gte", models.F("opened_observed_at")),
                    _connector="OR",
                ),
                name="vacancy_episode_closed_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="positioncountevidence",
            constraint=models.UniqueConstraint(
                fields=("posting_observation", "vacancy_episode", "extractor_version"),
                name="position_evidence_observation_episode_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="positioncountevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("positions_count__isnull", True), ("positions_count__gt", 0), _connector="OR"
                ),
                name="position_evidence_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancypostingmembership",
            constraint=models.UniqueConstraint(
                fields=("posting", "identity_version"),
                name="vacancy_membership_posting_version_unique",
            ),
        ),
    ]
