# Generated by Django 5.1.15 on 2026-08-08 18:31

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedupRunVacancyState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_vacancy_key", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED_OBSERVED", "Closed observed")],
                        max_length=20,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("closed_observed_at", models.DateTimeField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(default=1)),
                ("positions_count", models.PositiveIntegerField(blank=True, null=True)),
                ("multi_hire_possible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "canonical_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_run_canonical_states",
                        to="observations.posting",
                    ),
                ),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancy_states",
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "vacancy_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_states",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "dedup_run_vacancy_state",
            },
        ),
        migrations.CreateModel(
            name="DedupRunPostingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "membership_role",
                    models.CharField(
                        choices=[("CANONICAL", "Canonical"), ("SUPPORTING", "Supporting")],
                        max_length=12,
                    ),
                ),
                (
                    "link_method",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("HARD_KEY", "Hard key"),
                            ("RULE_SCORE", "Rule score"),
                            ("HUMAN", "Human"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_assignments",
                        to="vacancies.dedupdecision",
                    ),
                ),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_assignments",
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_run_assignments",
                        to="observations.posting",
                    ),
                ),
                (
                    "run_vacancy_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_assignments",
                        to="vacancies.deduprunvacancystate",
                    ),
                ),
            ],
            options={
                "db_table": "dedup_run_posting_assignment",
            },
        ),
        migrations.AddConstraint(
            model_name="deduprunvacancystate",
            constraint=models.UniqueConstraint(
                fields=("dedup_run", "run_vacancy_key"), name="dedup_run_vacancy_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="deduprunvacancystate",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("first_seen_at"))),
                name="dedup_run_vacancy_seen_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="deduprunvacancystate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_observed_at__isnull", True),
                    ("closed_observed_at__gte", models.F("first_seen_at")),
                    _connector="OR",
                ),
                name="dedup_run_vacancy_closed_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="deduprunvacancystate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("positions_count__isnull", True), ("positions_count__gt", 0), _connector="OR"
                ),
                name="dedup_run_vacancy_positions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="deduprunpostingassignment",
            constraint=models.UniqueConstraint(
                fields=("dedup_run", "posting"), name="dedup_run_posting_assignment_unique"
            ),
        ),
    ]
