# Generated by Django 5.1.15 on 2026-08-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_deduprunvacancystate_deduprunpostingassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyProjectionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identity_version", models.CharField(max_length=50, unique=True)),
                ("applied_as_of", models.DateTimeField()),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vacancy_projection_state",
            },
        ),
        migrations.AddField(
            model_name="dedupreviewitem",
            name="run_vacancy_state_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_items_as_a",
                to="vacancies.deduprunvacancystate",
            ),
        ),
        migrations.AddField(
            model_name="dedupreviewitem",
            name="run_vacancy_state_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_items_as_b",
                to="vacancies.deduprunvacancystate",
            ),
        ),
        migrations.AlterField(
            model_name="dedupreviewitem",
            name="vacancy_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_items_as_a",
                to="vacancies.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="dedupreviewitem",
            name="vacancy_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_items_as_b",
                to="vacancies.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="deduprunvacancystate",
            name="vacancy_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="run_states",
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddConstraint(
            model_name="dedupreviewitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("run_vacancy_state_a__isnull", True),
                    ("run_vacancy_state_b__isnull", True),
                    models.Q(
                        ("run_vacancy_state_a", models.F("run_vacancy_state_b")), _negated=True
                    ),
                    _connector="OR",
                ),
                name="dedup_review_run_states_distinct",
            ),
        ),
        migrations.AddField(
            model_name="vacancyprojectionstate",
            name="applied_dedup_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_projection",
                to="vacancies.deduprun",
            ),
        ),
    ]
