# Generated by Django 5.1.15 on 2026-08-12 21:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0003_vacancyprojectionstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedupReviewDecisionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_fingerprint", models.CharField(max_length=64)),
                ("fingerprint_version", models.CharField(max_length=80)),
                (
                    "application_method",
                    models.CharField(default="MATERIAL_IDENTICAL_HUMAN_REUSE", max_length=50),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_human_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_reuse_applications",
                        to="vacancies.dedupdecision",
                    ),
                ),
                (
                    "target_algorithm_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inherited_review_application",
                        to="vacancies.dedupdecision",
                    ),
                ),
            ],
            options={
                "db_table": "dedup_review_decision_application",
            },
        ),
    ]
