# Generated by Django 5.1.15 on 2026-08-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("source_id", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("source_name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=255)),
                ("source_family", models.CharField(max_length=40)),
                ("source_type", models.CharField(max_length=50)),
                ("priority", models.CharField(max_length=10)),
                ("coverage_scope", models.CharField(max_length=255)),
                ("canonicality", models.CharField(max_length=50)),
                ("platform_family", models.CharField(blank=True, max_length=50)),
                ("access_method", models.CharField(max_length=30)),
                ("automation_status", models.CharField(max_length=50)),
                ("legal_review_status", models.CharField(max_length=50)),
                ("verification_status", models.CharField(max_length=50)),
                ("official_url", models.URLField(max_length=500)),
                ("search_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sources_source",
                "ordering": ["source_id"],
                "indexes": [
                    models.Index(
                        fields=["source_family", "priority"], name="sources_sou_source__cac46b_idx"
                    ),
                    models.Index(fields=["platform_family"], name="sources_sou_platfor_14a33b_idx"),
                ],
            },
        ),
    ]
