# Generated by Django 5.1.15 on 2026-08-07 21:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "core",
            "0002_rename_core_raw_artifact_sha256_idx_core_raw_ar_sha256__84b00a_idx",
        ),
        (
            "reference_data",
            "0002_premiumsignal_reference_premium_signal_weight_between_0_and_1_and_more",
        ),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("listing_url", models.URLField(max_length=500)),
                ("listings_discovered", models.PositiveIntegerField(default=0)),
                ("details_fetched", models.PositiveIntegerField(default=0)),
                ("observations_created", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "listing_raw_artifact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_collection_run",
                        to="core.rawartifact",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
            ],
            options={
                "db_table": "collection_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PostingObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_posting_id", models.CharField(max_length=100)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("canonical_url", models.URLField(max_length=500)),
                ("title", models.CharField(max_length=300)),
                ("date_posted", models.DateField(blank=True, null=True)),
                ("valid_through", models.DateField(blank=True, null=True)),
                ("employment_type", models.CharField(blank=True, max_length=80)),
                ("hiring_organization", models.CharField(blank=True, max_length=200)),
                ("description_html", models.TextField(blank=True)),
                ("responsibilities_html", models.TextField(blank=True)),
                ("qualifications_html", models.TextField(blank=True)),
                ("benefits_html", models.TextField(blank=True)),
                ("location_street", models.CharField(blank=True, max_length=200)),
                ("location_locality", models.CharField(blank=True, max_length=100)),
                ("location_region", models.CharField(blank=True, max_length=100)),
                ("location_postal_code", models.CharField(blank=True, max_length=20)),
                ("location_country", models.CharField(blank=True, max_length=2)),
                ("structured_payload", models.JSONField()),
                (
                    "collection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="observations.collectionrun",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_data.municipality",
                    ),
                ),
                (
                    "raw_artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_observation",
                        to="core.rawartifact",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
            ],
            options={
                "db_table": "posting_observation",
                "ordering": ["-observed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionrun",
            index=models.Index(
                fields=["source", "-started_at"], name="collection__source__3a4c72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionrun",
            index=models.Index(fields=["status"], name="collection__status_4105e7_idx"),
        ),
        migrations.AddIndex(
            model_name="postingobservation",
            index=models.Index(
                fields=["source", "source_posting_id", "-observed_at"],
                name="posting_obs_source__8dca7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postingobservation",
            index=models.Index(
                fields=["date_posted"], name="posting_obs_date_po_14ab41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postingobservation",
            index=models.Index(
                fields=["valid_through"], name="posting_obs_valid_t_d50241_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.UniqueConstraint(
                fields=("collection_run", "source_posting_id"),
                name="posting_observation_run_source_posting_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_through__gte", models.F("date_posted")),
                    ("date_posted__isnull", True),
                    ("valid_through__isnull", True),
                    _connector="OR",
                ),
                name="posting_observation_dates_ordered",
            ),
        ),
    ]
