# Generated by Django 5.1.15 on 2026-08-08 06:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrun",
            name="green_assessments_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="run_scope",
            field=models.CharField(
                choices=[("TARGETED", "Targeted"), ("FULL_SOURCE", "Full source")],
                default="TARGETED",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="snapshot_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="GreenRelevanceAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("classifier_version", models.CharField(max_length=80)),
                ("taxonomy_version", models.CharField(max_length=80)),
                ("taxonomy_sha256", models.CharField(max_length=64)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("GREEN_CONFIRMED", "Green confirmed"),
                            ("REVIEW", "Review"),
                            ("NOT_GREEN", "Not green"),
                        ],
                        max_length=20,
                    ),
                ),
                ("matched_positive_terms", models.JSONField(default=list)),
                ("matched_conditional_terms", models.JSONField(default=list)),
                ("matched_exclusion_terms", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="green_relevance_assessments",
                        to="observations.postingobservation",
                    ),
                ),
            ],
            options={
                "db_table": "green_relevance_assessment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["classifier_version", "result"],
                        name="green_relev_classif_e9c698_idx",
                    ),
                    models.Index(fields=["taxonomy_sha256"], name="green_relev_taxonom_5522ea_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("posting_observation", "classifier_version"),
                        name="green_assessment_observation_classifier_unique",
                    )
                ],
            },
        ),
    ]
