# Generated by Django 5.1.15 on 2026-08-08 07:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_postings(apps, schema_editor):
    Posting = apps.get_model("observations", "Posting")
    Observation = apps.get_model("observations", "PostingObservation")
    groups = (
        Observation.objects.values("source_id", "source_posting_id")
        .annotate(first_seen=models.Min("observed_at"), last_seen=models.Max("observed_at"))
        .order_by()
    )
    for group in groups:
        latest = (
            Observation.objects.filter(
                source_id=group["source_id"], source_posting_id=group["source_posting_id"]
            )
            .order_by("-observed_at")
            .first()
        )
        if latest is None:
            continue
        posting = Posting.objects.create(
            source_id=group["source_id"],
            source_posting_id=group["source_posting_id"],
            current_status="STILL_ACTIVE",
            first_seen_at=group["first_seen"],
            last_seen_at=group["last_seen"],
            latest_canonical_url=latest.canonical_url,
        )
        Observation.objects.filter(
            source_id=group["source_id"], source_posting_id=group["source_posting_id"]
        ).update(posting_id=posting.pk, observation_status="ACTIVE")


def reverse_backfill(apps, schema_editor):
    Observation = apps.get_model("observations", "PostingObservation")
    Posting = apps.get_model("observations", "Posting")
    Observation.objects.update(posting_id=None)
    Posting.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_core_raw_artifact_sha256_idx_core_raw_ar_sha256__84b00a_idx"),
        ("observations", "0002_collectionrun_green_assessments_created_and_more"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrun",
            name="listing_total_discovered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="negative_observations_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="postings_in_scope",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="source_health_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="source_health_status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("DEGRADED", "Degraded"),
                    ("OUTAGE", "Outage"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postingobservation",
            name="observation_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("NOT_FOUND", "Not found"),
                    ("EXPIRED_EXPLICIT", "Expired explicit"),
                    ("REDIRECTED", "Redirected"),
                    ("BLOCKED", "Blocked"),
                    ("ERROR", "Error"),
                    ("SOURCE_OUTAGE", "Source outage"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postingobservation",
            name="raw_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_observations",
                to="core.rawartifact",
            ),
        ),
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_posting_id", models.CharField(max_length=100)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("STILL_ACTIVE", "Still active"),
                            ("DISAPPEARED_PENDING", "Disappeared pending"),
                            ("CLOSED_OBSERVED", "Closed observed"),
                        ],
                        default="NEW",
                        max_length=24,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("first_negative_at", models.DateTimeField(blank=True, null=True)),
                ("last_negative_at", models.DateTimeField(blank=True, null=True)),
                ("closed_observed_at", models.DateTimeField(blank=True, null=True)),
                ("negative_scan_count", models.PositiveIntegerField(default=0)),
                ("latest_canonical_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
            ],
            options={
                "db_table": "posting",
            },
        ),
        migrations.AddField(
            model_name="postingobservation",
            name="posting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="observations.posting",
            ),
        ),
        migrations.RunPython(backfill_postings, reverse_backfill),
        migrations.CreateModel(
            name="PostingLifecycleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("STILL_ACTIVE", "Still active"),
                            ("DISAPPEARED_PENDING", "Disappeared pending"),
                            ("CLOSED_OBSERVED", "Closed observed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("source_health_status", models.CharField(max_length=10)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "collection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="observations.collectionrun",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="observations.posting",
                    ),
                ),
                (
                    "posting_observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_event",
                        to="observations.postingobservation",
                    ),
                ),
            ],
            options={
                "db_table": "posting_lifecycle_event",
                "ordering": ["observed_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(
                fields=["source", "current_status"], name="posting_source__3494e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(fields=["last_seen_at"], name="posting_last_se_87f461_idx"),
        ),
        migrations.AddConstraint(
            model_name="posting",
            constraint=models.UniqueConstraint(
                fields=("source", "source_posting_id"), name="posting_source_native_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="posting",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("first_seen_at"))),
                name="posting_seen_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="posting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_observed_at__isnull", True),
                    ("closed_observed_at__gte", models.F("last_seen_at")),
                    _connector="OR",
                ),
                name="posting_closed_after_last_seen",
            ),
        ),
        migrations.AddIndex(
            model_name="postinglifecycleevent",
            index=models.Index(
                fields=["posting", "observed_at"], name="posting_lif_posting_417f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postinglifecycleevent",
            index=models.Index(
                fields=["event_type", "observed_at"], name="posting_lif_event_t_12d9d4_idx"
            ),
        ),
    ]
