# Generated by Django 5.1.15 on 2026-08-08 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0003_temporal_lifecycle_source_health"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postingobservation",
            name="posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="observations.posting",
            ),
        ),
    ]
