# Generated by Django 5.1.15 on 2026-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0004_enforce_posting_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrun",
            name="listing_final_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="collectionrun",
            name="listing_http_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
