# Generated by Django 5.1.15 on 2026-08-08 10:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_core_raw_artifact_sha256_idx_core_raw_ar_sha256__84b00a_idx"),
        ("observations", "0005_not_found_listing_provenance"),
        (
            "reference_data",
            "0002_premiumsignal_reference_premium_signal_weight_between_0_and_1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PostingLocationResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("resolver_version", models.CharField(max_length=80)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("REVIEW", "Review"),
                            ("UNRESOLVED", "Unresolved"),
                        ],
                        max_length=12,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_precision",
                    models.CharField(
                        choices=[
                            ("EXACT_WORK_ADDRESS", "Exact work address"),
                            ("POSTCODE", "Postcode"),
                            ("MUNICIPALITY", "Municipality"),
                            ("DISTRICT_OR_REGION", "District or region"),
                            ("CANTON", "Canton"),
                            ("REMOTE_OR_MULTIPLE", "Remote or multiple"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "coordinate_source",
                    models.CharField(
                        choices=[
                            ("SOURCE_STRUCTURED", "Source structured"),
                            ("SOURCE_TEXT_GEOCODED", "Source text geocoded"),
                            ("SWISSTOPO_SEARCHSERVER", "swisstopo SearchServer"),
                            ("BFS_MUNICIPALITY_CENTROID", "BFS centroid"),
                            ("MANUAL_REVIEW", "Manual review"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                ("geocoding_confidence", models.FloatField(blank=True, null=True)),
                (
                    "privacy_display_level",
                    models.CharField(
                        choices=[
                            ("EXACT_ALLOWED", "Exact allowed"),
                            ("POSTCODE_CENTROID", "Postcode centroid"),
                            ("MUNICIPALITY_CENTROID", "Municipality centroid"),
                            ("REGION_CENTROID", "Region centroid"),
                            ("HIDDEN", "Hidden"),
                        ],
                        max_length=24,
                    ),
                ),
                ("public_display_latitude", models.FloatField(blank=True, null=True)),
                ("public_display_longitude", models.FloatField(blank=True, null=True)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_location_resolutions",
                        to="reference_data.municipality",
                    ),
                ),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_resolutions",
                        to="observations.postingobservation",
                    ),
                ),
            ],
            options={
                "db_table": "posting_location_resolution",
            },
        ),
        migrations.CreateModel(
            name="GeocodingReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=80)),
                ("candidate_evidence", models.JSONField(default=list)),
                ("resolver_version", models.CharField(max_length=80)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geocoding_reviews",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "location_resolution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_item",
                        to="observations.postinglocationresolution",
                    ),
                ),
            ],
            options={
                "db_table": "geocoding_review_item",
            },
        ),
        migrations.CreateModel(
            name="GeocoderCacheEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("provider_version", models.CharField(max_length=80)),
                ("normalized_request", models.JSONField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("requested_url", models.URLField(max_length=1000)),
                ("final_url", models.URLField(max_length=1000)),
                ("http_status", models.PositiveSmallIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("response_payload", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "raw_artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geocoder_cache_entry",
                        to="core.rawartifact",
                    ),
                ),
            ],
            options={
                "db_table": "geocoder_cache_entry",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_version", "request_fingerprint"),
                        name="geocoder_cache_provider_request_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="postinglocationresolution",
            index=models.Index(
                fields=["resolver_version", "resolution_status"],
                name="posting_loc_resolve_bd6139_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postinglocationresolution",
            index=models.Index(
                fields=["municipality", "location_precision"], name="posting_loc_municip_fd16d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postinglocationresolution",
            index=models.Index(fields=["input_fingerprint"], name="posting_loc_input_f_fe528d_idx"),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.UniqueConstraint(
                fields=("posting_observation", "resolver_version"),
                name="location_resolution_observation_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="location_resolution_latitude_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="location_resolution_longitude_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_display_latitude__isnull", True),
                    models.Q(
                        ("public_display_latitude__gte", -90), ("public_display_latitude__lte", 90)
                    ),
                    _connector="OR",
                ),
                name="location_resolution_public_lat_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_display_longitude__isnull", True),
                    models.Q(
                        ("public_display_longitude__gte", -180),
                        ("public_display_longitude__lte", 180),
                    ),
                    _connector="OR",
                ),
                name="location_resolution_public_lon_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("geocoding_confidence__isnull", True),
                    models.Q(("geocoding_confidence__gte", 0), ("geocoding_confidence__lte", 1)),
                    _connector="OR",
                ),
                name="location_resolution_confidence_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="geocodingreviewitem",
            index=models.Index(
                fields=["review_status", "resolver_version"], name="geocoding_r_review__d4c68c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geocodingreviewitem",
            index=models.Index(fields=["reason"], name="geocoding_r_reason_ac86a0_idx"),
        ),
    ]
