# Generated by Django 5.1.15 on 2026-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0006_postinglocationresolution_geocodingreviewitem_and_more"),
        (
            "reference_data",
            "0002_premiumsignal_reference_premium_signal_weight_between_0_and_1_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="location_resolution_coordinate_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("public_display_latitude__isnull", True),
                        ("public_display_longitude__isnull", True),
                    ),
                    models.Q(
                        ("public_display_latitude__isnull", False),
                        ("public_display_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="location_resolution_public_coordinate_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("privacy_display_level", "HIDDEN"), _negated=True),
                    models.Q(
                        ("public_display_latitude__isnull", True),
                        ("public_display_longitude__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="location_resolution_hidden_has_no_coordinates",
            ),
        ),
    ]
