# Generated by Django 5.1.15 on 2026-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "observations",
            "0007_postinglocationresolution_location_resolution_coordinate_pair_and_more",
        ),
        (
            "reference_data",
            "0002_premiumsignal_reference_premium_signal_weight_between_0_and_1_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postinglocationresolution",
            name="location_resolution_observation_version_unique",
        ),
        migrations.AddField(
            model_name="postinglocationresolution",
            name="privacy_context",
            field=models.CharField(
                choices=[
                    ("PUBLIC_OR_NON_RESIDENTIAL", "Public or non-residential"),
                    ("PRIVATE_RESIDENCE", "Private residence"),
                    ("CONFIDENTIAL_PRIVATE_RESIDENCE", "Confidential private residence"),
                ],
                default="PUBLIC_OR_NON_RESIDENTIAL",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglocationresolution",
            constraint=models.UniqueConstraint(
                fields=("posting_observation", "resolver_version", "privacy_context"),
                name="location_resolution_observation_version_privacy_unique",
            ),
        ),
    ]
