# Generated by Django 5.1.15 on 2026-08-12 15:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenRelevanceReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("CONFIRMED_GREEN", "Confirmed green"),
                            ("CONFIRMED_NOT_GREEN", "Confirmed not green"),
                            ("INSUFFICIENT_EVIDENCE", "Insufficient evidence"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("reason", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("governance_version", models.CharField(max_length=80)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="observations.greenrelevanceassessment",
                    ),
                ),
            ],
            options={
                "db_table": "green_relevance_review_decision",
                "ordering": ["reviewed_at", "created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["assessment", "reviewed_at", "created_at"],
                        name="green_relev_assessm_5f6516_idx",
                    ),
                    models.Index(
                        fields=["governance_version", "outcome"],
                        name="green_relev_governa_b51f6c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "governance_version", "reviewed_at"),
                        name="green_review_decision_assessment_version_time_unique",
                    )
                ],
            },
        ),
    ]
