# Generated by Django 5.1.15 on 2026-08-12 21:18

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0010_greenrelevancereviewdecision"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenRelevanceReviewDecisionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_fingerprint", models.CharField(max_length=64)),
                ("fingerprint_version", models.CharField(max_length=80)),
                ("governance_version", models.CharField(max_length=80)),
                (
                    "application_method",
                    models.CharField(default="MATERIAL_IDENTICAL_HUMAN_REUSE", max_length=50),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuse_applications",
                        to="observations.greenrelevancereviewdecision",
                    ),
                ),
                (
                    "target_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_applications",
                        to="observations.greenrelevanceassessment",
                    ),
                ),
            ],
            options={
                "db_table": "green_relevance_review_decision_application",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_assessment", "governance_version"),
                        name="green_review_application_target_version_unique",
                    )
                ],
            },
        ),
    ]
