# Generated by Django 5.1.15 on 2026-08-13 09:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0002_dashboard_audit_integrity"),
        ("day0", "0002_source_policy_and_freshness"),
        ("observations", "0011_greenrelevancereviewdecisionapplication"),
        ("premium_segments", "0003_premiumsegmentassessment_green_result_origin_and_more"),
        ("sources", "0002_sourceendpoint"),
        ("vacancies", "0004_dedupreviewdecisionapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservatoryCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cycle_version", models.CharField(max_length=80)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("RECOVERY", "Recovery"),
                        ],
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("SUCCEEDED_NOT_AUTHORIZED", "Succeeded, not authorized"),
                            ("FAILED_COLLECTION", "Collection failed"),
                            ("FAILED_COMPLETENESS", "Completeness failed"),
                            ("FAILED_CONTINUITY", "Continuity failed"),
                            ("FAILED_DEDUP", "Dedup failed"),
                            ("FAILED_PREMIUM", "Premium failed"),
                            ("FAILED_DASHBOARD", "Dashboard failed"),
                            ("FAILED_READINESS", "Readiness failed"),
                            ("ABORTED_CONCURRENCY", "Concurrency refused"),
                        ],
                        default="PLANNED",
                        max_length=40,
                    ),
                ),
                ("target_cohort_version", models.CharField(max_length=80)),
                ("selected_source_ids", models.JSONField(default=list)),
                ("configuration", models.JSONField(default=dict)),
                ("configuration_fingerprint", models.CharField(max_length=64)),
                ("stage_statuses", models.JSONField(blank=True, default=dict)),
                ("final_cutoff", models.DateTimeField(blank=True, null=True)),
                (
                    "operational_health",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("AMBER", "Amber"),
                            ("RED", "Red"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                ("quality_state", models.JSONField(blank=True, default=dict)),
                ("continuity_counts", models.JSONField(blank=True, default=dict)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_evidence", models.JSONField(blank=True, default=dict)),
                ("code_git_sha", models.CharField(default="UNKNOWN", max_length=64)),
                (
                    "dashboard_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboardsnapshot",
                    ),
                ),
                (
                    "dedup_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "premium_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="premium_segments.premiumsegmentrun",
                    ),
                ),
                (
                    "readiness_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="day0.day0readinessassessment",
                    ),
                ),
            ],
            options={
                "db_table": "observatory_cycle",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ObservatorySourceAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("REUSED", "Reused in same-cycle retry"),
                        ],
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("runtime_ms", models.PositiveBigIntegerField(default=0)),
                ("run_status", models.CharField(blank=True, max_length=20)),
                ("source_health", models.CharField(blank=True, max_length=20)),
                ("snapshot_complete", models.BooleanField(default=False)),
                ("counter_consistent", models.BooleanField(default=False)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_detail", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "collection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="observations.collectionrun",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_attempts",
                        to="operations.observatorycycle",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
            ],
            options={
                "db_table": "observatory_source_attempt",
                "ordering": ["cycle_id", "source_id", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="OperationalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("artifact_type", models.CharField(blank=True, max_length=80)),
                ("artifact_id", models.CharField(blank=True, max_length=100)),
                ("detail", models.JSONField(default=dict)),
                ("deduplication_fingerprint", models.CharField(max_length=64)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_events",
                        to="operations.observatorycycle",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "db_table": "operational_event",
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="observatorycycle",
            index=models.Index(
                fields=["status", "-requested_at"], name="observatory_status_cdbfef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observatorycycle",
            index=models.Index(
                fields=["cycle_version", "-finished_at"], name="observatory_cycle_v_1127b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="observatorycycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("configuration_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="observatory_cycle_configuration_fp_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="observatorycycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_cutoff__isnull", True), ("finished_at__isnull", False), _connector="OR"
                ),
                name="observatory_cycle_cutoff_requires_finish",
            ),
        ),
        migrations.AddConstraint(
            model_name="observatorysourceattempt",
            constraint=models.UniqueConstraint(
                fields=("cycle", "source", "attempt_number"),
                name="observatory_source_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="observatorysourceattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result", "FAILED"), ("collection_run__isnull", False), _connector="OR"
                ),
                name="observatory_success_attempt_has_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalevent",
            constraint=models.UniqueConstraint(
                fields=("cycle", "deduplication_fingerprint"),
                name="operational_event_cycle_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("deduplication_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="operational_event_fp_valid",
            ),
        ),
    ]
