# Generated by Django 5.1.15 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observatorycycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("SUCCEEDED_NOT_AUTHORIZED", "Succeeded, not authorized"),
                    ("FAILED_COLLECTION", "Collection failed"),
                    ("FAILED_COMPLETENESS", "Completeness failed"),
                    ("FAILED_CONTINUITY", "Continuity failed"),
                    ("FAILED_DEDUP", "Dedup failed"),
                    ("FAILED_PREMIUM", "Premium failed"),
                    ("FAILED_GEOSPATIAL", "Geospatial resolution failed"),
                    ("FAILED_DASHBOARD", "Dashboard failed"),
                    ("FAILED_READINESS", "Readiness failed"),
                    ("ABORTED_CONCURRENCY", "Concurrency refused"),
                ],
                default="PLANNED",
                max_length=40,
            ),
        ),
    ]
