# Generated by Django 5.1.15 on 2026-08-10 10:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0002_dashboard_audit_integrity"),
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
        ("premium_segments", "0001_initial"),
        ("sources", "0002_sourceendpoint"),
        ("vacancies", "0003_vacancyprojectionstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day0SourceUniverse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("universe_version", models.CharField(max_length=80)),
                ("policy_version", models.CharField(max_length=80)),
                (
                    "threshold_policy_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted")], max_length=12
                    ),
                ),
                (
                    "required_completion_threshold",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("source_registry_sha256", models.CharField(max_length=64)),
                ("coverage_matrix_sha256", models.CharField(max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "day0_source_universe",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe_version", "input_fingerprint"),
                        name="day0_universe_version_input_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_registry_sha256__regex", "^[0-9a-f]{64}$")),
                        name="day0_universe_registry_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coverage_matrix_sha256__regex", "^[0-9a-f]{64}$")),
                        name="day0_universe_coverage_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="day0_universe_fingerprint_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("required_completion_threshold__isnull", True),
                                ("threshold_policy_status", "PENDING"),
                            ),
                            models.Q(
                                ("required_completion_threshold__gt", 0),
                                ("required_completion_threshold__lte", 1),
                                ("threshold_policy_status", "ACCEPTED"),
                            ),
                            _connector="OR",
                        ),
                        name="day0_universe_threshold_policy_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Day0ReadinessAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("readiness_version", models.CharField(max_length=80)),
                ("as_of", models.DateTimeField()),
                ("policy_version", models.CharField(max_length=80)),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("DAY_0_AUTHORIZED", "Day-0 authorized"),
                            ("DAY_0_NOT_READY", "Day-0 not ready"),
                            ("DAY_0_THRESHOLD_POLICY_PENDING", "Day-0 threshold policy pending"),
                            ("DAY_0_BLOCKED_BY_SOURCE_ACCESS", "Day-0 blocked by source access"),
                            ("DAY_0_BLOCKED_BY_DATA_QUALITY", "Day-0 blocked by data quality"),
                        ],
                        max_length=40,
                    ),
                ),
                ("selected_source_ids", models.JSONField(default=list)),
                ("selected_collection_run_ids", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=dict)),
                ("critical_review_ids", models.JSONField(default=list)),
                ("noncritical_review_ids", models.JSONField(default=list)),
                ("blockers", models.JSONField(default=list)),
                ("required_source_count", models.PositiveIntegerField()),
                ("supporting_source_count", models.PositiveIntegerField()),
                ("deferred_source_count", models.PositiveIntegerField()),
                ("blocked_source_count", models.PositiveIntegerField()),
                ("implemented_required_source_count", models.PositiveIntegerField()),
                ("required_full_source_healthy_count", models.PositiveIntegerField()),
                (
                    "required_source_completion_ratio",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
                ),
                (
                    "healthy_source_ratio",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
                ),
                ("critical_review_count", models.PositiveIntegerField()),
                ("noncritical_review_count", models.PositiveIntegerField()),
                ("observed_postings", models.PositiveIntegerField()),
                ("active_unique_vacancies", models.PositiveIntegerField()),
                ("known_positions_total", models.PositiveIntegerField()),
                ("vacancies_unknown_position_count", models.PositiveIntegerField()),
                ("multi_hire_possible_count", models.PositiveIntegerField()),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dashboard_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboardsnapshot",
                    ),
                ),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="vacancies.deduprun"
                    ),
                ),
                (
                    "premium_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="premium_segments.premiumsegmentrun",
                    ),
                ),
                (
                    "source_universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="day0.day0sourceuniverse",
                    ),
                ),
            ],
            options={
                "db_table": "day0_readiness_assessment",
                "ordering": ["-as_of", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Day0SourceUniverseEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("DAY0_REQUIRED", "Day-0 required"),
                            ("DAY0_SUPPORTING", "Day-0 supporting"),
                            ("DEFERRED", "Deferred"),
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("BLOCKED_PENDING_ACCESS_REVIEW", "Blocked pending access review"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required"),
                            ("SUPPORTING", "Supporting"),
                            ("NONE", "None"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField()),
                ("source_name", models.CharField(max_length=200)),
                ("source_family", models.CharField(max_length=80)),
                ("source_type", models.CharField(max_length=80)),
                ("priority", models.CharField(max_length=12)),
                ("coverage_scope", models.CharField(max_length=200)),
                ("canonicality", models.CharField(max_length=80)),
                ("platform_family", models.CharField(max_length=100)),
                ("automation_status", models.CharField(max_length=100)),
                ("legal_review_status", models.CharField(max_length=100)),
                ("verification_status", models.CharField(max_length=100)),
                ("existing_adapter_reuse", models.BooleanField(default=False)),
                ("new_adapter_required", models.BooleanField(default=False)),
                ("blocking_issue", models.TextField(blank=True)),
                ("implementation_batch", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="day0.day0sourceuniverse",
                    ),
                ),
            ],
            options={
                "db_table": "day0_source_universe_entry",
                "ordering": ["implementation_batch", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="Day0ReadinessSourceEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("COMPLETE_HEALTHY", "Complete and healthy"),
                            ("NO_ELIGIBLE_RUN", "No eligible run"),
                            ("DEGRADED", "Degraded"),
                            ("OUTAGE", "Outage"),
                            ("INCOMPLETE", "Incomplete"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("is_healthy", models.BooleanField(default=False)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_evidence",
                        to="day0.day0readinessassessment",
                    ),
                ),
                (
                    "collection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="observations.collectionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sources.source"
                    ),
                ),
                (
                    "universe_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="day0.day0sourceuniverseentry",
                    ),
                ),
            ],
            options={
                "db_table": "day0_readiness_source_evidence",
                "ordering": ["source_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_universe",
                    "as_of",
                    "dedup_run",
                    "premium_run",
                    "dashboard_snapshot",
                    "input_fingerprint",
                ),
                name="day0_readiness_exact_input_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="day0_readiness_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("implemented_required_source_count__lte", models.F("required_source_count"))
                ),
                name="day0_implemented_required_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_full_source_healthy_count__lte", models.F("required_source_count"))
                ),
                name="day0_healthy_required_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_source_completion_ratio__isnull", True),
                    models.Q(
                        ("required_source_completion_ratio__gte", 0),
                        ("required_source_completion_ratio__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="day0_required_ratio_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("healthy_source_ratio__isnull", True),
                    models.Q(("healthy_source_ratio__gte", 0), ("healthy_source_ratio__lte", 1)),
                    _connector="OR",
                ),
                name="day0_health_ratio_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0sourceuniverseentry",
            constraint=models.UniqueConstraint(
                fields=("universe", "source"), name="day0_universe_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="day0sourceuniverseentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("implementation_batch__isnull", True), ("target_role", "NONE")),
                    models.Q(
                        ("implementation_batch__isnull", False),
                        ("target_role__in", ["REQUIRED", "SUPPORTING"]),
                    ),
                    _connector="OR",
                ),
                name="day0_entry_batch_matches_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinesssourceevidence",
            constraint=models.UniqueConstraint(
                fields=("assessment", "universe_entry"), name="day0_readiness_source_entry_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinesssourceevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completion_status", "COMPLETE_HEALTHY"), _negated=True),
                    models.Q(
                        ("collection_run__isnull", False),
                        ("is_complete", True),
                        ("is_healthy", True),
                    ),
                    _connector="OR",
                ),
                name="day0_complete_healthy_evidence_coherent",
            ),
        ),
    ]
