# Generated by Django 5.1.15 on 2026-08-10 14:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_dashboard_audit_integrity"),
        ("day0", "0001_initial"),
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
        ("premium_segments", "0001_initial"),
        ("sources", "0002_sourceendpoint"),
        ("vacancies", "0003_vacancyprojectionstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day0AuthorizationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("policy_version", models.CharField(max_length=80, unique=True)),
                (
                    "threshold_policy_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted")], max_length=12
                    ),
                ),
                (
                    "required_completion_threshold",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "freshness_policy_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted")], max_length=12
                    ),
                ),
                (
                    "required_source_max_age_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("input_fingerprint", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "day0_authorization_policy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="day0readinessassessment",
            name="day0_readiness_exact_input_unique",
        ),
        migrations.RemoveConstraint(
            model_name="day0readinesssourceevidence",
            name="day0_complete_healthy_evidence_coherent",
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="blocked_other_source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="blocked_required_source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="blocked_supporting_source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="critical_dedup_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="critical_green_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="green_confirmed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="green_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="missing_green_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="not_applicable_source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="not_green_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="other_critical_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="required_complete_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="required_freshness_valid_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="required_healthy_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="selected_source_postings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="currently_healthy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="freshness_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="latest_activity_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day0_latest_activity_evidence",
                to="observations.collectionrun",
            ),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="latest_full_source_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day0_latest_full_source_evidence",
                to="observations.collectionrun",
            ),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="latest_health_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day0_latest_health_evidence",
                to="observations.collectionrun",
            ),
        ),
        migrations.AddField(
            model_name="day0readinesssourceevidence",
            name="structurally_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="day0sourceuniverseentry",
            name="access_reason",
            field=models.TextField(default="Legacy source-universe entry"),
        ),
        migrations.AddField(
            model_name="day0sourceuniverseentry",
            name="access_status",
            field=models.CharField(
                choices=[
                    ("READY_FOR_IMPLEMENTATION", "Ready for implementation"),
                    ("BLOCKED_PENDING_ACCESS_REVIEW", "Blocked pending access review"),
                    ("NOT_APPLICABLE", "Not applicable"),
                    ("UNKNOWN_LEGACY", "Unknown legacy"),
                ],
                default="UNKNOWN_LEGACY",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="day0sourceuniverseentry",
            name="canton_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="day0readinessassessment",
            name="blockers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="day0readinessassessment",
            name="critical_review_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="day0readinessassessment",
            name="noncritical_review_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="day0readinessassessment",
            name="selected_collection_run_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="day0readinesssourceevidence",
            name="collection_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day0_legacy_selected_evidence",
                to="observations.collectionrun",
            ),
        ),
        migrations.AlterField(
            model_name="day0readinesssourceevidence",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("COMPLETE_HEALTHY", "Complete and healthy"),
                    ("COMPLETE_FRESHNESS_PENDING", "Complete; freshness pending"),
                    ("NO_ELIGIBLE_RUN", "No eligible run"),
                    ("DEGRADED", "Degraded"),
                    ("OUTAGE", "Outage"),
                    ("INCOMPLETE", "Incomplete"),
                    ("FAILED", "Failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinesssourceevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completion_status", "COMPLETE_HEALTHY"), _negated=True),
                    models.Q(
                        ("currently_healthy", True),
                        ("freshness_valid", True),
                        ("is_complete", True),
                        ("is_healthy", True),
                        ("latest_full_source_run__isnull", False),
                        ("latest_health_run__isnull", False),
                        ("structurally_complete", True),
                    ),
                    models.Q(
                        ("collection_run__isnull", False),
                        ("freshness_valid__isnull", True),
                        ("is_complete", True),
                        ("is_healthy", True),
                        ("latest_full_source_run__isnull", True),
                        ("latest_health_run__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="day0_complete_healthy_v2_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0authorizationpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="day0_policy_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0authorizationpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("required_completion_threshold__isnull", True),
                        ("threshold_policy_status", "PENDING"),
                    ),
                    models.Q(
                        ("required_completion_threshold__gt", 0),
                        ("required_completion_threshold__lte", 1),
                        ("threshold_policy_status", "ACCEPTED"),
                    ),
                    _connector="OR",
                ),
                name="day0_policy_threshold_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0authorizationpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("freshness_policy_status", "PENDING"),
                        ("required_source_max_age_hours__isnull", True),
                    ),
                    models.Q(
                        ("freshness_policy_status", "ACCEPTED"),
                        ("required_source_max_age_hours__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="day0_policy_freshness_coherent",
            ),
        ),
        migrations.AddField(
            model_name="day0readinessassessment",
            name="authorization_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="day0.day0authorizationpolicy",
            ),
        ),
        migrations.AddConstraint(
            model_name="day0readinessassessment",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_universe",
                    "authorization_policy",
                    "as_of",
                    "dedup_run",
                    "premium_run",
                    "dashboard_snapshot",
                    "input_fingerprint",
                ),
                name="day0_readiness_v2_exact_input_unique",
            ),
        ),
    ]
