# Generated by Django 5.1.15 on 2026-08-13 14:01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("day0", "0002_source_policy_and_freshness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day0authorizationpolicy",
            name="policy_version",
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name="Day0AuthorizationPolicyDesignation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("designation_version", models.CharField(max_length=80)),
                ("policy_version", models.CharField(max_length=80)),
                (
                    "authority_basis",
                    models.CharField(
                        choices=[("MERGED_GOVERNANCE_DECISION", "Merged governance decision")],
                        max_length=40,
                    ),
                ),
                ("governance_evidence", models.JSONField(default=dict)),
                ("effective_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("input_fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "authoritative_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_designations",
                        to="day0.day0authorizationpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "day0_authorization_policy_designation",
                "ordering": ["-effective_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("designation_version", "policy_version"),
                        name="day0_policy_designation_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="day0_policy_designation_fingerprint_valid",
                    ),
                ],
            },
        ),
    ]
