# Generated by Django 5.1.15 on 2026-08-10 08:16
# ruff: noqa: E501

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
        ("premium_segments", "0001_initial"),
        ("vacancies", "0003_vacancyprojectionstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dashboard_version", models.CharField(max_length=40)),
                ("as_of", models.DateTimeField()),
                ("dedup_version", models.CharField(max_length=40)),
                ("premium_classifier_version", models.CharField(max_length=80)),
                ("green_classifier_version", models.CharField(max_length=80)),
                ("geospatial_resolver_version", models.CharField(max_length=80)),
                ("source_link_policy_version", models.CharField(max_length=80)),
                ("configuration", models.JSONField(default=dict)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("total_vacancy_states", models.PositiveIntegerField()),
                ("public_green_eligible_count", models.PositiveIntegerField()),
                ("excluded_not_green_count", models.PositiveIntegerField()),
                ("review_not_public_count", models.PositiveIntegerField()),
                ("mappable_vacancy_count", models.PositiveIntegerField()),
                ("unmappable_vacancy_count", models.PositiveIntegerField()),
                ("known_publication_date_count", models.PositiveIntegerField()),
                ("unknown_publication_date_count", models.PositiveIntegerField()),
                ("geospatial_resolved_count", models.PositiveIntegerField()),
                ("geospatial_review_count", models.PositiveIntegerField()),
                ("geospatial_unresolved_count", models.PositiveIntegerField()),
                ("private_location_protected_count", models.PositiveIntegerField()),
                ("dedup_review_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dedup_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_snapshots",
                        to="vacancies.deduprun",
                    ),
                ),
                (
                    "premium_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_snapshots",
                        to="premium_segments.premiumsegmentrun",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_snapshot",
                "ordering": ["-as_of", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardVacancyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_vacancy_key", models.CharField(max_length=64)),
                (
                    "visibility_status",
                    models.CharField(
                        choices=[
                            ("PUBLIC_GREEN_CONFIRMED", "Public green confirmed"),
                            ("EXCLUDED_NOT_GREEN", "Excluded not green"),
                            ("REVIEW_NOT_PUBLIC", "Review not public"),
                            ("MISSING_GREEN_ASSESSMENT", "Missing green assessment"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("MAPPABLE", "Mappable"),
                            ("LOCATION_UNRESOLVED", "Location unresolved"),
                            ("LOCATION_REVIEW", "Location review"),
                            ("PUBLIC_COORDINATES_MISSING", "Public coordinates missing"),
                            ("PRIVACY_RESOLUTION_MISSING", "Privacy resolution missing"),
                            ("LOCATION_HIDDEN", "Location hidden"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_link_status",
                    models.CharField(
                        choices=[
                            ("CANONICAL", "Canonical"),
                            ("AGENCY_CANONICAL", "Agency canonical"),
                            ("ORIGINAL_ATS_LINKED", "Original ATS linked"),
                            ("PORTAL_KNOWN_URL_PENDING", "Portal URL pending"),
                            ("DISCOVERY_OR_HISTORICAL", "Discovery or historical"),
                            ("EXPIRED_SOURCE", "Expired source"),
                            ("NO_LINK_AVAILABLE", "No link available"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=32,
                    ),
                ),
                ("selected_external_url", models.URLField(blank=True, max_length=1000)),
                ("visible_link_label", models.CharField(blank=True, max_length=40)),
                ("link_selection_method", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=300)),
                ("employer", models.CharField(blank=True, max_length=200)),
                ("safe_description", models.TextField(blank=True)),
                ("vacancy_status", models.CharField(max_length=20)),
                ("municipality_name", models.CharField(blank=True, max_length=100)),
                ("canton_code", models.CharField(blank=True, max_length=2)),
                ("source_published_date", models.DateField(blank=True, null=True)),
                ("published_at_precision", models.CharField(max_length=30)),
                ("published_at_parse_method", models.CharField(max_length=40)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("closed_observed_at", models.DateTimeField(blank=True, null=True)),
                ("location_precision", models.CharField(max_length=24)),
                ("privacy_context", models.CharField(max_length=32)),
                ("privacy_display_level", models.CharField(max_length=24)),
                ("public_display_latitude", models.FloatField(blank=True, null=True)),
                ("public_display_longitude", models.FloatField(blank=True, null=True)),
                ("premium_segment", models.CharField(max_length=40)),
                ("premium_assessment_status", models.CharField(max_length=30)),
                ("source_name", models.CharField(max_length=100)),
                ("source_type", models.CharField(max_length=50)),
                ("canonical_url", models.URLField(blank=True, max_length=1000)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("workload", models.CharField(blank=True, max_length=100)),
                ("positions_count", models.PositiveIntegerField(blank=True, null=True)),
                ("multi_hire_possible", models.BooleanField(default=False)),
                ("episode_number", models.PositiveIntegerField()),
                ("source_provenance", models.JSONField(default=list)),
                ("quality_flags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "canonical_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "canonical_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="observations.posting",
                    ),
                ),
                (
                    "dedup_run_vacancy_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="vacancies.deduprunvacancystate",
                    ),
                ),
                (
                    "green_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="observations.greenrelevanceassessment",
                    ),
                ),
                (
                    "location_resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="observations.postinglocationresolution",
                    ),
                ),
                (
                    "premium_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_records",
                        to="premium_segments.premiumsegmentassessment",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancy_records",
                        to="dashboard.dashboardsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_vacancy_record",
                "ordering": ["-first_seen_at", "run_vacancy_key"],
            },
        ),
        migrations.AddConstraint(
            model_name="dashboardsnapshot",
            constraint=models.UniqueConstraint(
                fields=("dashboard_version", "as_of", "input_fingerprint"),
                name="dashboard_snapshot_exact_input_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="dashboard_snapshot_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_vacancy_states",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("public_green_eligible_count"),
                                "+",
                                models.F("excluded_not_green_count"),
                            ),
                            "+",
                            models.F("review_not_public_count"),
                        ),
                    )
                ),
                name="dashboard_snapshot_visibility_counts_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "public_green_eligible_count",
                        django.db.models.expressions.CombinedExpression(
                            models.F("mappable_vacancy_count"),
                            "+",
                            models.F("unmappable_vacancy_count"),
                        ),
                    )
                ),
                name="dashboard_snapshot_mapping_counts_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardvacancyrecord",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "dedup_run_vacancy_state"),
                name="dashboard_record_snapshot_state_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardvacancyrecord",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "run_vacancy_key"), name="dashboard_record_snapshot_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardvacancyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("public_display_latitude__isnull", True),
                        ("public_display_longitude__isnull", True),
                    ),
                    models.Q(
                        ("public_display_latitude__isnull", False),
                        ("public_display_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dashboard_record_public_coordinate_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardvacancyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mapping_status", "MAPPABLE"), _negated=True),
                    models.Q(
                        ("public_display_latitude__isnull", False),
                        ("public_display_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dashboard_record_mappable_has_coordinates",
            ),
        ),
    ]
