# Generated by Django 5.1.15 on 2026-08-09 21:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfileEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("employer_name", models.CharField(max_length=300)),
                ("evidence_text", models.TextField()),
                ("evidence_type", models.CharField(max_length=50)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("available_at", models.DateTimeField()),
                ("raw_sha256", models.CharField(max_length=64)),
                ("evidence_version", models.CharField(max_length=50)),
                ("provenance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "premium_employer_profile_evidence",
                "indexes": [
                    models.Index(
                        fields=["employer_name", "available_at"],
                        name="premium_emp_employe_5db3a6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("classifier_version", models.CharField(max_length=80)),
                ("normalizer_version", models.CharField(max_length=80)),
                ("taxonomy_version", models.CharField(max_length=80)),
                ("taxonomy_sha256", models.CharField(max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("observations_considered", models.PositiveIntegerField(default=0)),
                ("green_confirmed_eligible", models.PositiveIntegerField(default=0)),
                ("classified_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("no_sufficient_evidence_count", models.PositiveIntegerField(default=0)),
                ("skipped_not_green_count", models.PositiveIntegerField(default=0)),
                ("private_residential_standard_count", models.PositiveIntegerField(default=0)),
                ("private_residential_premium_count", models.PositiveIntegerField(default=0)),
                ("private_estate_direct_count", models.PositiveIntegerField(default=0)),
                ("unknown_count", models.PositiveIntegerField(default=0)),
                ("prohibited_inference_only_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")], max_length=12
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField()),
            ],
            options={
                "db_table": "premium_segment_run",
                "ordering": ["-as_of", "-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "as_of",
                            "classifier_version",
                            "normalizer_version",
                            "taxonomy_sha256",
                            "input_fingerprint",
                        ),
                        name="premium_run_exact_input_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("PRIVATE_RESIDENTIAL_STANDARD", "Private residential standard"),
                            ("PRIVATE_RESIDENTIAL_PREMIUM", "Private residential premium"),
                            ("PRIVATE_ESTATE_DIRECT", "Private estate direct"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "assessment_status",
                    models.CharField(
                        choices=[
                            ("CLASSIFIED", "Classified"),
                            ("REVIEW", "Review"),
                            ("NO_SUFFICIENT_EVIDENCE", "No sufficient evidence"),
                            ("SKIPPED_NOT_GREEN", "Skipped not green"),
                        ],
                        max_length=30,
                    ),
                ),
                ("method", models.CharField(max_length=50)),
                (
                    "evidence_strength",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MODERATE", "Moderate"),
                            ("WEAK", "Weak"),
                            ("NONE", "None"),
                        ],
                        max_length=12,
                    ),
                ),
                ("matched_signal_ids", models.JSONField(default=list)),
                ("matched_fields_and_scopes", models.JSONField(default=list)),
                ("matched_evidence", models.JSONField(default=list)),
                ("prohibited_inferences", models.JSONField(default=list)),
                (
                    "privacy_context",
                    models.CharField(
                        choices=[
                            ("PUBLIC_OR_NON_RESIDENTIAL", "Public or non-residential"),
                            ("PRIVATE_RESIDENCE", "Private residence"),
                            ("CONFIDENTIAL_PRIVATE_RESIDENCE", "Confidential private residence"),
                        ],
                        default="PUBLIC_OR_NON_RESIDENTIAL",
                        max_length=32,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employer_profile_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="premium_segments.employerprofileevidence",
                    ),
                ),
                (
                    "green_relevance_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="observations.greenrelevanceassessment",
                    ),
                ),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="observations.postingobservation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="premium_segments.premiumsegmentrun",
                    ),
                ),
            ],
            options={
                "db_table": "premium_segment_assessment",
                "ordering": ["run_id", "posting_observation_id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("conflicting_or_insufficient_evidence", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending")], default="PENDING", max_length=12
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_item",
                        to="premium_segments.premiumsegmentassessment",
                    ),
                ),
            ],
            options={
                "db_table": "premium_segment_review_item",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status", "PENDING")),
                        name="premium_review_initial_status_pending",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="premiumsegmentassessment",
            index=models.Index(
                fields=["assessment_status", "segment"], name="premium_seg_assessm_40d63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="premiumsegmentassessment",
            index=models.Index(
                fields=["posting_observation", "created_at"], name="premium_seg_posting_acfcdc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentassessment",
            constraint=models.UniqueConstraint(
                fields=("run", "posting_observation"),
                name="premium_assessment_run_observation_unique",
            ),
        ),
    ]
