# Generated by Django 5.1.15 on 2026-08-10 00:04

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observations", "0009_collectionrunfetch_nullable_observation_municipality"),
        ("sources", "0002_sourceendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfileEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("employer_identity_key", models.CharField(max_length=200)),
                ("employer_name", models.CharField(max_length=300)),
                ("evidence_text", models.TextField()),
                ("evidence_type", models.CharField(max_length=50)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("available_at", models.DateTimeField()),
                (
                    "raw_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="value must be a lowercase 64-character SHA-256 digest",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("evidence_version", models.CharField(max_length=50)),
                ("provenance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_employer_evidence",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "db_table": "premium_employer_profile_evidence",
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("PRIVATE_RESIDENTIAL_STANDARD", "Private residential standard"),
                            ("PRIVATE_RESIDENTIAL_PREMIUM", "Private residential premium"),
                            ("PRIVATE_ESTATE_DIRECT", "Private estate direct"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "assessment_status",
                    models.CharField(
                        choices=[
                            ("CLASSIFIED", "Classified"),
                            ("REVIEW", "Review"),
                            ("NO_SUFFICIENT_EVIDENCE", "No sufficient evidence"),
                            ("SKIPPED_NOT_GREEN", "Skipped not green"),
                        ],
                        max_length=30,
                    ),
                ),
                ("method", models.CharField(max_length=50)),
                (
                    "evidence_strength",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MODERATE", "Moderate"),
                            ("WEAK", "Weak"),
                            ("NONE", "None"),
                        ],
                        max_length=12,
                    ),
                ),
                ("matched_signal_ids", models.JSONField(blank=True, default=list)),
                ("matched_fields_and_scopes", models.JSONField(blank=True, default=list)),
                ("matched_evidence", models.JSONField(blank=True, default=list)),
                ("prohibited_inferences", models.JSONField(blank=True, default=list)),
                (
                    "privacy_context",
                    models.CharField(
                        choices=[
                            ("PUBLIC_OR_NON_RESIDENTIAL", "Public or non-residential"),
                            ("PRIVATE_RESIDENCE", "Private residence"),
                            ("CONFIDENTIAL_PRIVATE_RESIDENCE", "Confidential private residence"),
                        ],
                        default="PUBLIC_OR_NON_RESIDENTIAL",
                        max_length=32,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employer_profile_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="premium_segments.employerprofileevidence",
                    ),
                ),
                (
                    "green_relevance_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="observations.greenrelevanceassessment",
                    ),
                ),
                (
                    "posting_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premium_segment_assessments",
                        to="observations.postingobservation",
                    ),
                ),
            ],
            options={
                "db_table": "premium_segment_assessment",
                "ordering": ["run_id", "posting_observation_id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentAssessmentEmployerEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employer_evidence_links",
                        to="premium_segments.premiumsegmentassessment",
                    ),
                ),
                (
                    "employer_profile_evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_links",
                        to="premium_segments.employerprofileevidence",
                    ),
                ),
            ],
            options={
                "db_table": "premium_segment_assessment_employer_evidence",
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "conflicting_or_insufficient_evidence",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending")], default="PENDING", max_length=12
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_item",
                        to="premium_segments.premiumsegmentassessment",
                    ),
                ),
            ],
            options={
                "db_table": "premium_segment_review_item",
            },
        ),
        migrations.CreateModel(
            name="PremiumSegmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("classifier_version", models.CharField(max_length=80)),
                ("normalizer_version", models.CharField(max_length=80)),
                ("taxonomy_version", models.CharField(max_length=80)),
                (
                    "taxonomy_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="value must be a lowercase 64-character SHA-256 digest",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                (
                    "input_fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="value must be a lowercase 64-character SHA-256 digest",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("observations_considered", models.PositiveIntegerField(default=0)),
                ("green_confirmed_eligible", models.PositiveIntegerField(default=0)),
                ("classified_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("no_sufficient_evidence_count", models.PositiveIntegerField(default=0)),
                ("skipped_not_green_count", models.PositiveIntegerField(default=0)),
                ("private_residential_standard_count", models.PositiveIntegerField(default=0)),
                ("private_residential_premium_count", models.PositiveIntegerField(default=0)),
                ("private_estate_direct_count", models.PositiveIntegerField(default=0)),
                ("unknown_count", models.PositiveIntegerField(default=0)),
                ("prohibited_inference_only_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")], max_length=12
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField()),
            ],
            options={
                "db_table": "premium_segment_run",
                "ordering": ["-as_of", "-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "as_of",
                            "classifier_version",
                            "normalizer_version",
                            "taxonomy_sha256",
                            "input_fingerprint",
                        ),
                        name="premium_run_exact_input_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("taxonomy_sha256__regex", "^[0-9a-f]{64}$")),
                        name="premium_run_taxonomy_sha256_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="premium_run_input_fingerprint_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("finished_at__gte", models.F("started_at"))),
                        name="premium_run_timestamps_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "observations_considered",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("classified_count"),
                                            "+",
                                            models.F("review_count"),
                                        ),
                                        "+",
                                        models.F("no_sufficient_evidence_count"),
                                    ),
                                    "+",
                                    models.F("skipped_not_green_count"),
                                ),
                            )
                        ),
                        name="premium_run_status_counts_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "observations_considered",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("private_residential_standard_count"),
                                            "+",
                                            models.F("private_residential_premium_count"),
                                        ),
                                        "+",
                                        models.F("private_estate_direct_count"),
                                    ),
                                    "+",
                                    models.F("unknown_count"),
                                ),
                            )
                        ),
                        name="premium_run_segment_counts_complete",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="premiumsegmentassessment",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="premium_segments.premiumsegmentrun",
            ),
        ),
        migrations.AddIndex(
            model_name="employerprofileevidence",
            index=models.Index(
                fields=["source", "employer_identity_key", "available_at"],
                name="premium_emp_source__ecb152_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerprofileevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("raw_sha256__regex", "^[0-9a-f]{64}$")),
                name="premium_profile_raw_sha256_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerprofileevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("employer_identity_key", ""), _negated=True),
                name="premium_profile_identity_key_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerprofileevidence",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "employer_identity_key",
                    "available_at",
                    "raw_sha256",
                    "evidence_version",
                ),
                name="premium_profile_material_evidence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentassessmentemployerevidence",
            constraint=models.UniqueConstraint(
                fields=("assessment", "employer_profile_evidence"),
                name="premium_assessment_employer_evidence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentreviewitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "PENDING")),
                name="premium_review_initial_status_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="premiumsegmentassessment",
            index=models.Index(
                fields=["assessment_status", "segment"], name="premium_seg_assessm_40d63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="premiumsegmentassessment",
            index=models.Index(
                fields=["posting_observation", "created_at"], name="premium_seg_posting_acfcdc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentassessment",
            constraint=models.UniqueConstraint(
                fields=("run", "posting_observation"),
                name="premium_assessment_run_observation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assessment_status", "CLASSIFIED"),
                        (
                            "segment__in",
                            [
                                "PRIVATE_RESIDENTIAL_STANDARD",
                                "PRIVATE_RESIDENTIAL_PREMIUM",
                                "PRIVATE_ESTATE_DIRECT",
                            ],
                        ),
                    ),
                    models.Q(
                        (
                            "assessment_status__in",
                            ["REVIEW", "NO_SUFFICIENT_EVIDENCE", "SKIPPED_NOT_GREEN"],
                        ),
                        ("segment", "UNKNOWN"),
                    ),
                    _connector="OR",
                ),
                name="premium_assessment_status_segment_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumsegmentassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("segment", "UNKNOWN"),
                    ("privacy_context", "PRIVATE_RESIDENCE"),
                    ("privacy_context", "CONFIDENTIAL_PRIVATE_RESIDENCE"),
                    _connector="OR",
                ),
                name="premium_assessment_private_segment_protected",
            ),
        ),
    ]
