# Generated by Django 5.1.15 on 2026-08-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rawartifact',
            new_name='core_raw_ar_sha256__84b00a_idx',
            old_name='core_raw_artifact_sha256_idx',
        ),
    ]
