# Generated by Django 5.1.15 on 2026-08-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                ("bfs_code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("snapshot_date", models.DateField()),
                ("municipality_name", models.CharField(max_length=100)),
                ("canton_code", models.CharField(max_length=2)),
                ("canton_name", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("bfs_language_region_code", models.PositiveSmallIntegerField()),
                ("language_region", models.CharField(max_length=30)),
                ("statistical_city", models.BooleanField()),
                ("degurb2021", models.PositiveSmallIntegerField()),
                ("priority_tier", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "reference_municipality",
                "ordering": ["bfs_code"],
                "indexes": [
                    models.Index(fields=["canton_code"], name="reference_m_canton__a1bb3f_idx"),
                    models.Index(
                        fields=["statistical_city"], name="reference_m_statist_87b9fc_idx"
                    ),
                    models.Index(fields=["degurb2021"], name="reference_m_degurb2_e9987b_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("degurb2021__in", [1, 2, 3])),
                        name="reference_municipality_degurb_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PremiumSignal",
            fields=[
                ("signal_id", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("signal_group", models.CharField(max_length=40)),
                ("search_term", models.CharField(max_length=100)),
                ("evidence_scope", models.CharField(max_length=30)),
                ("base_weight", models.DecimalField(decimal_places=4, max_digits=5)),
                ("default_segment", models.CharField(max_length=40)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reference_premium_signal",
                "ordering": ["signal_id"],
                "indexes": [
                    models.Index(fields=["signal_group"], name="reference_p_signal__f678c2_idx"),
                    models.Index(fields=["default_segment"], name="reference_p_default_9f7a02_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleSearchTerm",
            fields=[
                ("term_id", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("canonical_role_family", models.CharField(max_length=40)),
                ("canonical_specialization", models.CharField(max_length=40)),
                ("search_term_de", models.CharField(max_length=100)),
                ("term_type", models.CharField(max_length=30)),
                ("include_default", models.CharField(max_length=20)),
                ("public_relevance", models.CharField(max_length=20)),
                ("default_access_level_hint", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reference_role_search_term",
                "ordering": ["term_id"],
                "indexes": [
                    models.Index(
                        fields=["canonical_role_family"], name="reference_r_canonic_a9517e_idx"
                    ),
                    models.Index(
                        fields=["term_type", "include_default"],
                        name="reference_r_term_ty_3f98ee_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryReference",
            fields=[
                (
                    "reference_id",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("reference_type", models.CharField(max_length=40)),
                ("reference_scope", models.CharField(max_length=150)),
                ("qualification_level", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(max_length=3)),
                ("gross_net", models.CharField(max_length=10)),
                ("amount_monthly_raw", models.CharField(blank=True, max_length=50)),
                (
                    "amount_monthly_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "amount_monthly_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("payments_per_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("amount_annual_raw", models.CharField(blank=True, max_length=50)),
                (
                    "amount_annual_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "amount_annual_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("amount_hourly_base_raw", models.CharField(blank=True, max_length=50)),
                (
                    "amount_hourly_base_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "amount_hourly_base_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("applicability", models.CharField(max_length=80)),
                ("source_tier", models.CharField(max_length=50)),
                ("source_url", models.URLField(max_length=500)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reference_salary",
                "ordering": ["reference_id"],
                "indexes": [
                    models.Index(fields=["reference_type"], name="reference_s_referen_8d8a4a_idx"),
                    models.Index(
                        fields=["valid_from", "valid_to"], name="reference_s_valid_f_7dbce1_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_monthly_min__gte", 0),
                            ("amount_monthly_min__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_monthly_min_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_monthly_max__gte", models.F("amount_monthly_min")),
                            ("amount_monthly_max__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_monthly_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_annual_min__gte", 0),
                            ("amount_annual_min__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_annual_min_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_annual_max__gte", models.F("amount_annual_min")),
                            ("amount_annual_max__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_annual_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_hourly_base_min__gte", 0),
                            ("amount_hourly_base_min__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_hourly_min_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_hourly_base_max__gte", models.F("amount_hourly_base_min")),
                            ("amount_hourly_base_max__isnull", True),
                            _connector="OR",
                        ),
                        name="reference_salary_hourly_range_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CityPortalAudit",
            fields=[
                ("queue_id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("priority", models.CharField(max_length=10)),
                ("canton_code", models.CharField(max_length=2)),
                ("municipality_name", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("degurb2021", models.PositiveSmallIntegerField()),
                ("canonical_portal_url", models.URLField(blank=True, max_length=500)),
                ("platform_family", models.CharField(max_length=50)),
                ("portal_audit_status", models.CharField(max_length=30)),
                ("green_unit_hint", models.CharField(blank=True, max_length=255)),
                ("search_query_1", models.TextField()),
                ("search_query_2", models.TextField()),
                ("acceptance_test", models.TextField()),
                (
                    "municipality",
                    models.OneToOneField(
                        db_column="bfs_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_portal_audit",
                        to="reference_data.municipality",
                    ),
                ),
            ],
            options={
                "db_table": "reference_city_portal_audit",
                "ordering": ["queue_id"],
                "indexes": [
                    models.Index(
                        fields=["portal_audit_status"], name="reference_c_portal__00f0b0_idx"
                    ),
                    models.Index(fields=["platform_family"], name="reference_c_platfor_436554_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicEmployer",
            fields=[
                ("universe_id", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("employer_level", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=2)),
                ("canton_code", models.CharField(blank=True, max_length=2)),
                ("canton_name", models.CharField(blank=True, max_length=100)),
                ("employer_name", models.CharField(max_length=150)),
                ("language_region", models.CharField(max_length=30)),
                ("priority_tier", models.CharField(max_length=40)),
                ("expected_green_service_units", models.TextField(blank=True)),
                ("canonical_portal_status", models.CharField(max_length=30)),
                ("canonical_portal_url", models.URLField(blank=True, max_length=500)),
                ("portal_platform", models.CharField(blank=True, max_length=50)),
                ("verification_status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "municipality",
                    models.OneToOneField(
                        blank=True,
                        db_column="bfs_code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_employer",
                        to="reference_data.municipality",
                    ),
                ),
            ],
            options={
                "db_table": "reference_public_employer",
                "ordering": ["universe_id"],
                "indexes": [
                    models.Index(fields=["employer_level"], name="reference_p_employe_363438_idx"),
                    models.Index(fields=["canton_code"], name="reference_p_canton__fd1ebe_idx"),
                    models.Index(fields=["priority_tier"], name="reference_p_priorit_598987_idx"),
                ],
            },
        ),
    ]
