# Generated by Django 5.1.15 on 2026-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="premiumsignal",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_weight__gte", 0), ("base_weight__lte", 1)),
                name="reference_premium_signal_weight_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="salaryreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payments_per_year__gt", 0),
                    ("payments_per_year__isnull", True),
                    _connector="OR",
                ),
                name="reference_salary_payments_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salaryreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__gte", models.F("valid_from")),
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    _connector="OR",
                ),
                name="reference_salary_valid_period_ordered",
            ),
        ),
    ]
